exclude: '\.d.ts$'
repos:
  - repo: https://github.com/prettier/prettier
    rev: 1.18.2
    hooks:
      - id: prettier
        entry: prettier --write
        files: "\\.(ts|tsx)$"
        args:
          - --trailing-comma
          - es5
