version: '3'
services:
  web:
    container_name: flu-api-web
    build:
      context: ../..
      dockerfile: ./FluApi/docker/api/Dockerfile
    image: flu-api
    networks:
      - vpc
    ports:
      - "127.0.0.1:3000:3000"
      - "127.0.0.1:3200:3200"
    env_file: ../.env
    environment:
      - NODE_ENV=development
      - PII_DATABASE_URL=postgres://postgres@flu-api-db:5432/pii
      - NONPII_DATABASE_URL=postgres://postgres@flu-api-db:5432/nonpii
      - POSTGIS_DATABASE_URL=postgres://postgres@flu-api-db:5432/postgis
  postgis:
    container_name: flu-api-db
    image: mdillon/postgis:latest
    networks:
      - vpc
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/flu-api-init.sql

networks:
  vpc:
