version: '2.1'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow

    webserver:
        image: my-kube-airflow:latest
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
        volumes:
            - ~/git/audere/Pipeline/workflows/:/usr/local/airflow/dags
            - ~/.kube/:/kube
            # - ./dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    postgis:
        image: mdillon/postgis:10-alpine
        hostname: database
        environment:
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=pass
        ports:
            - "5432:5432"
        volumes:
            - ./init:/docker-entrypoint-initdb.d
